const data = [
{
    id: 1,
    title: "Learn Wedding Photography",
    description: "sdhbfhf jqhfwjvhaj  n fbmasfvh fgj kenjn ,dn, dn,n,d",
    price: 127,
    city: "new york",
    coverImg: "Chariot.jpg",
    stats: {
        rating: 5.9,
        reviewCount: 20,
    },
    location: "Online",
    openSpots: 27,
},
{
    id: 2,
    title: "Learn Wedding Photography",
    description: "sdhbfhf jqhfwjvhaj  n fbmasfvh fgj kenjn ,dn, dn,n,d",
    price: 128,
    city: "new york",
    coverImg: "CityofGold.jpg",
    stats: {
        rating: 5.9,
        reviewCount: 20,
    },
    location: "Online",
    openSpots: 27,
},
{
    id: 3,
    title: "Learn Wedding Photography",
    description: "sdhbfhf jqhfwjvhaj  n fbmasfvh fgj kenjn ,dn, dn,n,d",
    price: 129,
    city: "new york",
    coverImg: "NoSex.jpg",
    stats: {
        rating: 5.9,
        reviewCount: 20,
    },
    location: "Online",
    openSpots: 27,
},
{
    id: 4,
    title: "Learn Wedding Photography",
    description: "sdhbfhf jqhfwjvhaj  n fbmasfvh fgj kenjn ,dn, dn,n,d",
    price: 130,
    city: "new york",
    coverImg: "LionKing.jpg",
    stats: {
        rating: 5.9,
        reviewCount: 20,
    },
    location: "Online",
    openSpots: 27,
},
{
    id: 5,
    title: "Learn Wedding Photography",
    description: "sdhbfhf jqhfwjvhaj  n fbmasfvh fgj kenjn ,dn, dn,n,d",
    price: 131,
    city: "new york",
    coverImg: "joker.jpg",
    stats: {
        rating: 5.9,
        reviewCount: 20,
    },
    location: "Online",
    openSpots: 27,
},
{
    id: 6,
    title: "Learn Wedding Photography",
    description: "sdhbfhf jqhfwjvhaj  n fbmasfvh fgj kenjn ,dn, dn,n,d",
    price: 132,
    city: "new york",
    coverImg: "OlympusHasFallen.jpg",
    stats: {
        rating: 5.9,
        reviewCount: 20,
    },
    location: "Online",
    openSpots: 27,
},
{
    id: 7,
    title: "Learn Wedding Photography",
    description: "sdhbfhf jqhfwjvhaj  n fbmasfvh fgj kenjn ,dn, dn,n,d",
    price: 133,
    city: "new york",
    coverImg: "WireRoom.jpg",
    stats: {
        rating: 5.9,
        reviewCount: 20,
    },
    location: "Online",
    openSpots: 27,
},
{
    id: 8,
    title: "Learn Wedding Photography",
    description: "sdhbfhf jqhfwjvhaj  n fbmasfvh fgj kenjn ,dn, dn,n,d",
    price: 134,
    city: "new york",
    coverImg: "CityofGold.jpg",
    stats: {
        rating: 5.9,
        reviewCount: 20,
    },
    location: "Online",
    openSpots: 27,
},
{
    id: 9,
    title: "Learn Wedding Photography",
    description: "sdhbfhf jqhfwjvhaj  n fbmasfvh fgj kenjn ,dn, dn,n,d",
    price: 135,
    city: "new york",
    coverImg: "horror.jpg",
    stats: {
        rating: 5.9,
        reviewCount: 20,
    },
    location: "Online",
    openSpots: 27,
},
{
    id: 10,
    title: "Learn Wedding Photography",
    description: "sdhbfhf jqhfwjvhaj  n fbmasfvh fgj kenjn ,dn, dn,n,d",
    price: 128,
    city: "new york",
    coverImg: "hobbit.jpg",
    stats: {
        rating: 5.9,
        reviewCount: 20,
    },
    location: "Online",
    openSpots: 27,
},
{
    id: 11,
    title: "Learn Wedding Photography",
    description: "sdhbfhf jqhfwjvhaj  n fbmasfvh fgj kenjn ,dn, dn,n,d",
    price: 136,
    city: "new york",
    coverImg: "avatar.jpg",
    stats: {
        rating: 5.9,
        reviewCount: 20,
    },
    location: "Online",
    openSpots: 27,
},
{
    id: 12,
    title: "Learn Wedding Photography",
    description: "sdhbfhf jqhfwjvhaj  n fbmasfvh fgj kenjn ,dn, dn,n,d",
    price: 140,
    city: "new york",
    coverImg: "jumanji.jpg",
    stats: {
        rating: 5.9,
        reviewCount: 20,
    },
    location: "Online",
    openSpots: 27,
},
]

export default data